modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="random_tids_and_bits"
version="1.0.0"
displayName="random tids and bits"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Aidan, MCreator"

[[dependencies.random_tids_and_bits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




